package:
  name: hello_python
  version: 0.1.0

source:
  path: ../

build:
  number: 0
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - hello_python